apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice-deployment
  labels:
    app: dbservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbservice
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
      - name: dbservice
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_DB
          value: "dblibros"
        ports:
          - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appx-api-deployment
  labels:
    app: appx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appx-api
  template:
    metadata:
      labels:
        app: appx-api
    spec:
      containers:
      - name: appx-api-container
        image: micaelaa45/ddsdeploy
        ports:
        - containerPort: 8080
        env:
        - name: postgres_URL
          value: "postgresql://dbservice:5432/dblibros"
        - name: hibernate__hbm2ddl__auto
          value: "create"
        - name: javax__persistence__jdbc__driver
          value:  "org.postgresql.Driver"
        - name: javax__persistence__jdbc__password
          value: "123"
        - name: javax__persistence__jdbc__url
          value: "jdbc:postgresql://dbservice/dblibros"
        - name: javax__persistence__jdbc__user
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: appx-api-service
spec:
  selector:
    app: appx-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: dbservice
