 # Use postgres/example user/password credentials
version: "3.3"

services:
  dbservice:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dblibros
    volumes:
      - ./posgresdb:/var/lib/postgresql/data
    restart: always

  app:
    image: micaelaa45/ddsdeploy
    ports:
      - "8080:8080"
    environment:
       hibernate__hbm2ddl__auto: create
       javax__persistence__jdbc__driver: org.postgresql.Driver
       javax__persistence__jdbc__password: 123
       javax__persistence__jdbc__url: jdbc:postgresql://dbservice/dblibros
       javax__persistence__jdbc__user: postgres
    depends_on:
      - dbservice
    restart: always