services:
  prestashop:
    image: prestashop/prestashop:latest
    ports:
      - "8082:80"
    environment:
      - DB_SERVER=database
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - database
    restart: always

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:

