services:
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    
  prestashop:
    image: prestashop/prestashop:latest
    ports:
      - "8082:80"
    environment:
      - DB_SERVER=database
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - database
    restart: always
    
volumes:
  db_data:
