version: '3'

services:
  prestashop:
    image: prestashop/prestashop:latest
    ports:
      - "8082:80"
    environment:
      - DB_SERVER=database
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWORD=root

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
